name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools and platforms
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Gradle 8.7 via SDKMAN (with retry)
        env:
          SDKMAN_DIR: ${{ runner.temp }}/.sdkman
        run: |
          set -e
          curl -s "https://get.sdkman.io" | bash
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          for i in 1 2 3; do
            if sdk install gradle 8.7; then break; fi;
            echo "Retrying Gradle install ($i)"; sleep 5;
          done
          gradle -v

      - name: Build Debug APK (no wrapper)
        env:
          SDKMAN_DIR: ${{ runner.temp }}/.sdkman
        run: |
          set -e
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          for i in 1 2 3; do
            if gradle :app:assembleDebug; then break; fi;
            echo "Retrying Gradle build ($i)"; sleep 5;
          done

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: n8n-mobile-debug-apk
          path: app/build/outputs/apk/debug/*.apk
